// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package picollo

type Planning struct {
	Awal  *string `json:"awal"`
	Akhir *string `json:"akhir"`
}

func (Planning) IsWaktu() {}

type RencanaWaktu struct {
	Pemilihan   *Planning `json:"pemilihan"`
	Pelaksanaan *Planning `json:"pelaksanaan"`
	Pemanfaatan *Planning `json:"pemanfaatan"`
}

func (RencanaWaktu) IsWaktu() {}
