// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import model "picollo/model"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, id
func (_m *Service) Get(ctx context.Context, id string) (model.RupItem, error) {
	ret := _m.Called(ctx, id)

	var r0 model.RupItem
	if rf, ok := ret.Get(0).(func(context.Context, string) model.RupItem); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.RupItem)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rup provides a mock function with given fields: ctx, opt
func (_m *Service) Rup(ctx context.Context, opt model.RupOptions) ([]model.RupItem, error) {
	ret := _m.Called(ctx, opt)

	var r0 []model.RupItem
	if rf, ok := ret.Get(0).(func(context.Context, model.RupOptions) []model.RupItem); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RupItem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.RupOptions) error); ok {
		r1 = rf(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
