package scrapper

import (
	"context"
	"testing"

	model "picollo/model"

	"github.com/stretchr/testify/mock"
)

// mockScrapper is an autogenerated mock type for the Scrapper type
type mockScrapper struct {
	mock.Mock
}

// Scrape provides a mock function with given fields: url
func (_m *mockScrapper) Scrape(url string) (*Results, error) {
	ret := _m.Called(url)

	var r0 *Results
	if rf, ok := ret.Get(0).(func(string) *Results); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Results)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func TestNewmockScrapper(t *testing.T) {
	// var ctx context.Context = context.TODO()
	// var w waktu
	// Create a new instance of the mock store
	// c := colly.NewCollector()
	// r := new(mockStorage)

	// svc := model.NewService(r)
	m := new(mockScrapper)
	// In the "On" method, we assert that we want the "Get" method
	// to be called with one argument, that is 2
	// In the "Return" method, we define the return values to be 7, and nil (for the result and error values)
	m.On("Scrape", "abc").Return(nil, nil)
	// Next, we create a new instance of our module with the mock store as its "store" dependency
	// s := New(c, svc)
	// The "Get" method call is then made
	_, err := m.Scrape("abc")
	// The expectations that we defined for our mock store earlier are asserted here
	m.AssertExpectations(t)
	// Finally, we assert that we should'nt get any error
	if err != nil {
		t.Errorf("error should be nil, got: %v", err)
	}
}

// Storage is an autogenerated mock type for the Storage type
type mockStorage struct {
	mock.Mock
}

// AllRup provides a mock function with given fields: ctx
func (_m *mockStorage) AllRup(ctx context.Context) ([]model.RupItem, error) {
	ret := _m.Called(ctx)

	var r0 []model.RupItem
	if rf, ok := ret.Get(0).(func(context.Context) []model.RupItem); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RupItem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOpd provides a mock function with given fields: ctx, pkey
func (_m *mockStorage) GetOpd(ctx context.Context, pkey string) (model.RupRekapItem, error) {
	ret := _m.Called(ctx, pkey)

	var r0 model.RupRekapItem
	if rf, ok := ret.Get(0).(func(context.Context, string) model.RupRekapItem); ok {
		r0 = rf(ctx, pkey)
	} else {
		r0 = ret.Get(0).(model.RupRekapItem)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pkey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRup provides a mock function with given fields: ctx, pkey
func (_m *mockStorage) GetRup(ctx context.Context, pkey string) (model.RupItem, error) {
	ret := _m.Called(ctx, pkey)

	var r0 model.RupItem
	if rf, ok := ret.Get(0).(func(context.Context, string) model.RupItem); ok {
		r0 = rf(ctx, pkey)
	} else {
		r0 = ret.Get(0).(model.RupItem)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pkey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rup provides a mock function with given fields: ctx, opt
func (_m *mockStorage) Rup(ctx context.Context, opt model.RupOptions) ([]model.RupItem, error) {
	ret := _m.Called(ctx, opt)

	var r0 []model.RupItem
	if rf, ok := ret.Get(0).(func(context.Context, model.RupOptions) []model.RupItem); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RupItem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.RupOptions) error); ok {
		r1 = rf(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rups provides a mock function with given fields: ctx, opd
func (_m *mockStorage) Rups(ctx context.Context, opd model.RupRekapItem) ([]model.RupItem, error) {
	ret := _m.Called(ctx, opd)

	var r0 []model.RupItem
	if rf, ok := ret.Get(0).(func(context.Context, model.RupRekapItem) []model.RupItem); ok {
		r0 = rf(ctx, opd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RupItem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.RupRekapItem) error); ok {
		r1 = rf(ctx, opd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveOpd provides a mock function with given fields: ctx, objs
func (_m *mockStorage) SaveOpd(ctx context.Context, objs []model.RupRekapItem) error {
	ret := _m.Called(ctx, objs)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.RupRekapItem) error); ok {
		r0 = rf(ctx, objs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveRup provides a mock function with given fields: ctx, objs
func (_m *mockStorage) SaveRup(ctx context.Context, objs []model.RupItem) error {
	ret := _m.Called(ctx, objs)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.RupItem) error); ok {
		r0 = rf(ctx, objs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
